var personData2 = [
  {
    "name": "강남식",
    "id": 1,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강마야",
    "id": 2,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강문성",
    "id": 3,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "위스콘신대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강민정1",
    "id": 4,
    "vch1": "연세대",
    "vch2": "생화학",
    "doc1": "연세대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강병구",
    "id": 5,
    "vch1": "인하대",
    "vch2": "경제학",
    "doc1": "뉴욕주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강성태",
    "id": 6,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강성호",
    "id": 7,
    "vch1": "성균관대",
    "vch2": "경제학",
    "doc1": "성균관대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강신욱",
    "id": 8,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "강태중",
    "id": 9,
    "vch1": "서울대",
    "vch2": "교육학",
    "doc1": "위스콘신대",
    "doc2": "교육사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "강현석",
    "id": 10,
    "vch1": "경북대",
    "vch2": "교육학",
    "doc1": "경북대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "강현수",
    "id": 11,
    "vch1": "서울대",
    "vch2": "산업공학",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "한국공간환경학회",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "고길곤",
    "id": 12,
    "vch1": "연세대",
    "vch2": "응용통계학",
    "doc1": "피츠버그대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "고유환",
    "id": 13,
    "vch1": "동국대",
    "vch2": "정치학",
    "doc1": "동국대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "고혜원",
    "id": 14,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "이화여대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "구갑우",
    "id": 15,
    "vch1": "서울대",
    "vch2": "정치학",
    "doc1": "서울대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "구인회",
    "id": 16,
    "vch1": "서울대",
    "vch2": "철학",
    "doc1": "워싱턴대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "구자인",
    "id": 17,
    "vch1": "서울대",
    "vch2": "해양학",
    "doc1": "시마네대",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "구정화",
    "id": 18,
    "vch1": "서울대",
    "vch2": "사회교육",
    "doc1": "서울대",
    "doc2": "사회교육",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권문일",
    "id": 19,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권순원",
    "id": 20,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "코넬대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권오성1",
    "id": 21,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권오혁",
    "id": 22,
    "vch1": "서울대",
    "vch2": "지리학",
    "doc1": "서울대",
    "doc2": "행정학/환경계획학과",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권인숙",
    "id": 23,
    "vch1": "서울대",
    "vch2": "의류학",
    "doc1": "클라크대",
    "doc2": "여성학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "권혁",
    "id": 24,
    "vch1": "고려대",
    "vch2": "법학",
    "doc1": "마르부르크대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권현지",
    "id": 25,
    "vch1": "이화여대",
    "vch2": "사회학",
    "doc1": "코넬대",
    "doc2": "산업노동관계학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "권호열",
    "id": 26,
    "vch1": "서울대",
    "vch2": "전자공학",
    "doc1": "카이스트",
    "doc2": "전지전자공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "길현종",
    "id": 27,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "UCLA",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김갑성",
    "id": 28,
    "vch1": "연세대",
    "vch2": "건축공학",
    "doc1": "펜실베이니아대",
    "doc2": "지역경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김근주",
    "id": 29,
    "vch1": "한양대",
    "vch2": "법학",
    "doc1": "한양대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김기봉",
    "id": 30,
    "vch1": "성균관대",
    "vch2": "사학",
    "doc1": "빌레펠트대",
    "doc2": "철학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김기선",
    "id": 31,
    "vch1": "한양대",
    "vch2": "법학",
    "doc1": "라이프치히",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김기찬",
    "id": 32,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김남근",
    "id": 33,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "고려대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "김도훈",
    "id": 34,
    "vch1": "부경대",
    "vch2": "수산경영학",
    "doc1": "델라웨어대",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김동배",
    "id": 35,
    "vch1": "서울대",
    "vch2": "경영학",
    "doc1": "서울대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김동주",
    "id": 36,
    "vch1": "연세대",
    "vch2": "건축공학",
    "doc1": "펜실베이니아대",
    "doc2": "지역경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김두환",
    "id": 37,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "시카고대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김둘순",
    "id": 38,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "이화여대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김미곤",
    "id": 39,
    "vch1": "건국대",
    "vch2": "경제학",
    "doc1": "성균관대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김민희",
    "id": 40,
    "vch1": "한양대",
    "vch2": "교육학",
    "doc1": "서울대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김봉태",
    "id": 41,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김상곤1",
    "id": 42,
    "vch1": "서울대",
    "vch2": "경영학",
    "doc1": "서울대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김상조",
    "id": 43,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "김수연",
    "id": 44,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김수현1",
    "id": 45,
    "vch1": "서울대",
    "vch2": "도시공학",
    "doc1": "서울대",
    "doc2": "도시및지역계획학",
    "sch": "한국공간환경학회",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "김시곤",
    "id": 46,
    "vch1": "부산대",
    "vch2": "토목공학",
    "doc1": "버지니아공대",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김양희",
    "id": 47,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "도쿄대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김연명",
    "id": 48,
    "vch1": "중앙대",
    "vch2": "사회복지학",
    "doc1": "중앙대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "김연철",
    "id": 49,
    "vch1": "성균관대",
    "vch2": "정치외교학",
    "doc1": "성균관대",
    "doc2": "정치외교학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김영옥",
    "id": 50,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김용",
    "id": 51,
    "vch1": "서울대",
    "vch2": "교육학",
    "doc1": "서울대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김용익",
    "id": 52,
    "vch1": "서울대",
    "vch2": "의대",
    "doc1": "서울대",
    "doc2": "예방의학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김용창",
    "id": 53,
    "vch1": "서울대",
    "vch2": "지리학",
    "doc1": "서울대",
    "doc2": "지리학",
    "sch": "한국공간환경학회",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김용하",
    "id": 54,
    "vch1": "성균관대",
    "vch2": "경제학",
    "doc1": "성균관대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김원섭",
    "id": 55,
    "vch1": "고려대",
    "vch2": "사회학",
    "doc1": "브레멘대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김유선",
    "id": 56,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김유찬",
    "id": 57,
    "vch1": "서울대",
    "vch2": "원예학",
    "doc1": "함부르크대학교",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김윤자",
    "id": 58,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김은지",
    "id": 59,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김인재",
    "id": 60,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김재구",
    "id": 61,
    "vch1": "서울대",
    "vch2": "경영학",
    "doc1": "서울대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김재진1",
    "id": 62,
    "vch1": "서강대",
    "vch2": "경제학",
    "doc1": "미시간주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김정인1",
    "id": 63,
    "vch1": "서울대",
    "vch2": "역사교육",
    "doc1": "서울대",
    "doc2": "국사학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "김종엽",
    "id": 64,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "서울대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김종진1",
    "id": 65,
    "vch1": "가톨릭대",
    "vch2": "사회학",
    "doc1": "성공회대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김종훈",
    "id": 66,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "예일대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김주섭",
    "id": 67,
    "vch1": "한양대",
    "vch2": "경제학",
    "doc1": "아이오와주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김진방",
    "id": 68,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "듀크대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김진숙",
    "id": 69,
    "vch1": "이화여대",
    "vch2": "교육공학",
    "doc1": "이화여대",
    "doc2": "교육공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김진영1",
    "id": 70,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "로체스터대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김진우2",
    "id": 71,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "버밍엄대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김진욱",
    "id": 72,
    "vch1": "연세대",
    "vch2": "사회복지학",
    "doc1": "바스대",
    "doc2": "사회정책학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김창엽",
    "id": 73,
    "vch1": "서울대",
    "vch2": "의대",
    "doc1": "서울대",
    "doc2": "보건학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김태완1",
    "id": 74,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김태일1",
    "id": 75,
    "vch1": "고려대",
    "vch2": "정치외교학",
    "doc1": "고려대",
    "doc2": "정치외교학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김태헌",
    "id": 76,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김학수1",
    "id": 77,
    "vch1": "한국외대",
    "vch2": "경제학",
    "doc1": "오하이오주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김현경2",
    "id": 78,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "메사추세츠대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김현미",
    "id": 79,
    "vch1": "서울대",
    "vch2": "영어교육",
    "doc1": "워싱턴대",
    "doc2": "문화인류학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김현철1",
    "id": 80,
    "vch1": "연세대",
    "vch2": "화학공학",
    "doc1": "연세대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김현철2",
    "id": 81,
    "vch1": "서울대",
    "vch2": "경영학",
    "doc1": "게이오기주쿠대",
    "doc2": "비즈니스스쿨",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김현호",
    "id": 82,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김혜승",
    "id": 83,
    "vch1": "서울대",
    "vch2": "생활과학대학",
    "doc1": "경희대",
    "doc2": "주거정책",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김혜영2",
    "id": 84,
    "vch1": "고려대",
    "vch2": "사회학",
    "doc1": "고려대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김혜원",
    "id": 85,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "김홍상",
    "id": 86,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김흥종",
    "id": 87,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "김희삼",
    "id": 88,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "위스콘신대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "나영선",
    "id": 89,
    "vch1": "이화여대",
    "vch2": "사회학",
    "doc1": "이화여대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "나원준",
    "id": 90,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "남기곤",
    "id": 91,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "남기철",
    "id": 92,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "남영숙",
    "id": 93,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "스탠퍼드대",
    "doc2": "국제개발학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "남재량",
    "id": 94,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "남재욱",
    "id": 95,
    "vch1": "연세대",
    "vch2": "정치외교학",
    "doc1": "연세대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "남찬섭",
    "id": 96,
    "vch1": "연세대",
    "vch2": "사회복지학",
    "doc1": "연세대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "노광표",
    "id": 97,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "노대명",
    "id": 98,
    "vch1": "인하대",
    "vch2": "정치학",
    "doc1": "파리제2대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "노민선",
    "id": 99,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "중앙대",
    "doc2": "인적자원개발정책학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "노상헌",
    "id": 100,
    "vch1": "서울시립대",
    "vch2": "법학",
    "doc1": "도쿄대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "도재형",
    "id": 101,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "동용승",
    "id": 102,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "성균관대",
    "doc2": "무역학(수료)",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "류덕현",
    "id": 103,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "라이스대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "류방란",
    "id": 104,
    "vch1": "서울대",
    "vch2": "교육학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "류장수",
    "id": 105,
    "vch1": "경북대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "마강래",
    "id": 106,
    "vch1": "중앙대",
    "vch2": "응용통계학",
    "doc1": "런던대",
    "doc2": "도시계획학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "마경희",
    "id": 107,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "이화여대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "문미옥",
    "id": 108,
    "vch1": "포항공대",
    "vch2": "물리학",
    "doc1": "포항공대",
    "doc2": "물리학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "문성혁",
    "id": 109,
    "vch1": "한국해양대",
    "vch2": "항해학",
    "doc1": "카디프대",
    "doc2": "항만경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "문유경",
    "id": 110,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "문진영1",
    "id": 111,
    "vch1": "연세대",
    "vch2": "사회복지학",
    "doc1": "헐대",
    "doc2": "철학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "민소영",
    "id": 112,
    "vch1": "이화여대",
    "vch2": "정치외교학",
    "doc1": "펜실베이니아대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "민연주",
    "id": 113,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "메릴랜드대",
    "doc2": "교통학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박경서",
    "id": 114,
    "vch1": "고려대",
    "vch2": "경영학",
    "doc1": "노스웨스턴대",
    "doc2": "재무관리",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박경숙1",
    "id": 115,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "브라운대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박귀천",
    "id": 116,
    "vch1": "이화여대",
    "vch2": "법학",
    "doc1": "프랑크푸르트대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박기남",
    "id": 117,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박능후",
    "id": 118,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "버클리대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "박명준",
    "id": 119,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "쾰른대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박복영",
    "id": 120,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "박상희1",
    "id": 121,
    "vch1": "고려대",
    "vch2": "교육학",
    "doc1": "중앙대",
    "doc2": "육아교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "박선아",
    "id": 122,
    "vch1": "한양대",
    "vch2": "법학",
    "doc1": "한양대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박성호",
    "id": 123,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박소현",
    "id": 124,
    "vch1": "연세대",
    "vch2": "건축공학",
    "doc1": "워싱턴대",
    "doc2": "도시설계",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "박수경1",
    "id": 125,
    "vch1": "카이스트",
    "vch2": "기계공학",
    "doc1": "미시간대",
    "doc2": "기계공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박수근",
    "id": 126,
    "vch1": "연세대",
    "vch2": "법학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "박신영",
    "id": 127,
    "vch1": "이화여대",
    "vch2": "법학",
    "doc1": "연세대",
    "doc2": "도시행정",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "한국도시연구소",
    "thumb": null
  },
  {
    "name": "박영정",
    "id": 128,
    "vch1": "전남대",
    "vch2": "역사학",
    "doc1": "건국대",
    "doc2": "국문학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박은정1",
    "id": 129,
    "vch1": "이화여대",
    "vch2": "법학",
    "doc1": "프라이부르크대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "박은정2",
    "id": 130,
    "vch1": "이화여대",
    "vch2": "법학",
    "doc1": "이화여대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박정수1",
    "id": 131,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "피츠버그대",
    "doc2": "정책학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박준기",
    "id": 132,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박준식2",
    "id": 133,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박지순",
    "id": 134,
    "vch1": "고려대",
    "vch2": "법학",
    "doc1": "아우크스부르크대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박진",
    "id": 135,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "펜실베이니아대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박찬임",
    "id": 136,
    "vch1": "연세대",
    "vch2": 0,
    "doc1": "연세대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박창균",
    "id": 137,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "코넬대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박철우",
    "id": 138,
    "vch1": "연세대",
    "vch2": "기계공학",
    "doc1": "연세대",
    "doc2": "기계공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박태균",
    "id": 139,
    "vch1": "서울대",
    "vch2": "국사학",
    "doc1": "서울대",
    "doc2": "국사학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "박훈1",
    "id": 140,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "반상진",
    "id": 141,
    "vch1": "동국대",
    "vch2": "교육학",
    "doc1": "위스콘신대",
    "doc2": "교육행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "배규식",
    "id": 142,
    "vch1": "서울대",
    "vch2": "전자공학",
    "doc1": "워릭대",
    "doc2": "산업경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "배현기",
    "id": 143,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "백선희1",
    "id": 144,
    "vch1": "중앙대",
    "vch2": "사회복지학",
    "doc1": "중앙대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "백운규",
    "id": 145,
    "vch1": "한양대",
    "vch2": "세라믹공학",
    "doc1": "클렘슨대",
    "doc2": "세라믹공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "변재관",
    "id": 146,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "쯔쿠바대",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "변창흠",
    "id": 147,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "한국공간환경학회",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "환경정의",
    "thumb": true
  },
  {
    "name": "석재은",
    "id": 148,
    "vch1": "이화여대",
    "vch2": "사회복지학",
    "doc1": "이화여대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "설동훈",
    "id": 149,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "서울대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "성경륭",
    "id": 150,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "스탠퍼드대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "성기선",
    "id": 151,
    "vch1": "서울대",
    "vch2": "국어교육학",
    "doc1": "서울대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "성열관",
    "id": 152,
    "vch1": "고려대",
    "vch2": "교육학",
    "doc1": "위스콘신대",
    "doc2": "교육과정",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "손혁재",
    "id": 153,
    "vch1": "성균관대",
    "vch2": "정치외교학",
    "doc1": "성균관대",
    "doc2": "정치외교학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "송다영",
    "id": 154,
    "vch1": "연세대",
    "vch2": "영어영문학",
    "doc1": "펜실베이니아대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "송미령",
    "id": 155,
    "vch1": "이화여대",
    "vch2": "정치외교학",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "송병국",
    "id": 156,
    "vch1": "서울대",
    "vch2": "농촌사회교육",
    "doc1": "서울대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "송원근",
    "id": 157,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "신광영",
    "id": 158,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "위스콘신대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "신수정",
    "id": 159,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "신진욱",
    "id": 160,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "베를린자유대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "신현웅",
    "id": 161,
    "vch1": "연세대",
    "vch2": "보건행정학",
    "doc1": "고려대",
    "doc2": "보건학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "안성호",
    "id": 162,
    "vch1": "숭전대",
    "vch2": "영어영문학",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "양문수",
    "id": 163,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "도쿄대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "양병찬1",
    "id": 164,
    "vch1": "한국외대",
    "vch2": "영어교육",
    "doc1": "단국대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "양재진",
    "id": 165,
    "vch1": "연세대",
    "vch2": "행정학",
    "doc1": "럿거스대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "양창호",
    "id": 166,
    "vch1": "서강대",
    "vch2": "물류학",
    "doc1": "연세대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "양현아",
    "id": 167,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "뉴스쿨대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "어수봉",
    "id": 168,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "벤더빌트대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "오건호",
    "id": 169,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "서울대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "오성배",
    "id": 170,
    "vch1": "중앙대",
    "vch2": "교육학",
    "doc1": "중앙대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "오재학",
    "id": 171,
    "vch1": "서울대",
    "vch2": "산업공학",
    "doc1": "유니버시티칼리지런던",
    "doc2": "교통공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "유애정",
    "id": 172,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "유종일",
    "id": 173,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "하버드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "유태현",
    "id": 174,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "윤미경",
    "id": 175,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "옥스퍼드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "윤영진",
    "id": 176,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "함께하는시민행동",
    "thumb": null
  },
  {
    "name": "윤자영",
    "id": 177,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "메사추세츠대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "윤제용",
    "id": 178,
    "vch1": "서울대",
    "vch2": "공과대",
    "doc1": "뉴욕주립대",
    "doc2": "환경공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "윤종운",
    "id": 179,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "경기대",
    "doc2": "호텔경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "윤태범",
    "id": 180,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "윤홍식1",
    "id": 181,
    "vch1": "미주리대",
    "vch2": "경제학과",
    "doc1": "워싱턴대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "은기수",
    "id": 182,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "펜실베이니아대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이공주",
    "id": 183,
    "vch1": "이화여대",
    "vch2": "약학",
    "doc1": "스탠퍼드대",
    "doc2": "생물리화학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "이규용",
    "id": 184,
    "vch1": "전남대",
    "vch2": "경제학",
    "doc1": "성균관대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이근",
    "id": 185,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "버클리대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이남주",
    "id": 186,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "베이징대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "이동연",
    "id": 187,
    "vch1": "중앙대",
    "vch2": "영어영문학",
    "doc1": "중앙대",
    "doc2": "영어영문학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이레나",
    "id": 188,
    "vch1": "강원대",
    "vch2": "물리학",
    "doc1": "MIT",
    "doc2": "원자력공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이명헌",
    "id": 189,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "괴팅엔대",
    "doc2": "농업경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이문범",
    "id": 190,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이병훈1",
    "id": 191,
    "vch1": "서울대",
    "vch2": "사회학",
    "doc1": "코넬대",
    "doc2": "노사관계학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이병희",
    "id": 192,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이상준1",
    "id": 193,
    "vch1": "연세대",
    "vch2": "건축공학",
    "doc1": "베를린공대",
    "doc2": "공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이상준2",
    "id": 194,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이상호1",
    "id": 195,
    "vch1": "경북대",
    "vch2": "경제학",
    "doc1": "경북대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이상호3",
    "id": 196,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "브레멘대",
    "doc2": "노동경제",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이상희1",
    "id": 197,
    "vch1": "숭실대",
    "vch2": "법학",
    "doc1": "숭실대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이성우1",
    "id": 198,
    "vch1": "중앙대",
    "vch2": "지역개발학",
    "doc1": "USC",
    "doc2": "도시 및 지역계획학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이성우2",
    "id": 199,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울시립대",
    "doc2": "도시공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이소정",
    "id": 200,
    "vch1": "서울대",
    "vch2": 0,
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이수경1",
    "id": 201,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이승욱",
    "id": 202,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이시균",
    "id": 203,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이신해",
    "id": 204,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이영범1",
    "id": 205,
    "vch1": "연세대",
    "vch2": "행정학",
    "doc1": "오하이오주립대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이영범2",
    "id": 206,
    "vch1": "서울대",
    "vch2": "건축학",
    "doc1": "AA스쿨",
    "doc2": "도시공간이론",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이영훈",
    "id": 207,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이원재1",
    "id": 208,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이윤주",
    "id": 209,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이재영1",
    "id": 210,
    "vch1": "한양대",
    "vch2": "경영학",
    "doc1": "모스크바국립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "이정옥",
    "id": 211,
    "vch1": "서울대",
    "vch2": "영어교육",
    "doc1": "서울대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "이정우1",
    "id": 212,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "하버드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이정희1",
    "id": 213,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이제민",
    "id": 214,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "하버드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이종선",
    "id": 215,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "고려대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이주희1",
    "id": 216,
    "vch1": "이화여대",
    "vch2": "사회학",
    "doc1": "위스콘신대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이철수",
    "id": 217,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이태수",
    "id": 218,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "연세대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "이현주1",
    "id": 219,
    "vch1": "영남대",
    "vch2": "중어중문학",
    "doc1": "런민대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "이현주2",
    "id": 220,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "임강택",
    "id": 221,
    "vch1": "중앙대",
    "vch2": "경제학",
    "doc1": "뉴욕주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "임운택",
    "id": 222,
    "vch1": "한양대",
    "vch2": "사회학",
    "doc1": "마부르크 필립스대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "임원혁",
    "id": 223,
    "vch1": "스탠포드대",
    "vch2": "사학/물리학",
    "doc1": "스탠퍼드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "임혜숙",
    "id": 224,
    "vch1": "서울대",
    "vch2": "제어계측공학",
    "doc1": "텍사스주립대",
    "doc2": "전기컴퓨터공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "임후남",
    "id": 225,
    "vch1": "서울대",
    "vch2": "교육학",
    "doc1": "서울대",
    "doc2": "교육학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "장민기",
    "id": 226,
    "vch1": "서울대",
    "vch2": "경제학/농업자원경제학",
    "doc1": "서울대",
    "doc2": "농경제학(수료)",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "장영태",
    "id": 227,
    "vch1": "서울대",
    "vch2": "수의학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "장지상",
    "id": 228,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "장지연",
    "id": 229,
    "vch1": "연세대",
    "vch2": "영어영문학",
    "doc1": "위스콘신대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "장하성",
    "id": 230,
    "vch1": "고려대",
    "vch2": "경영학",
    "doc1": "펜실베이니아대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "장형수",
    "id": 231,
    "vch1": "한양대",
    "vch2": "경제학",
    "doc1": "브라운대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "전병목",
    "id": 232,
    "vch1": "서울대",
    "vch2": "자원공학",
    "doc1": "라이스대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "전병유",
    "id": 233,
    "vch1": "서울대",
    "vch2": "무역학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "전용일",
    "id": 234,
    "vch1": "연세대",
    "vch2": "경제학",
    "doc1": "UCSD",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "전현준",
    "id": 235,
    "vch1": "전남대",
    "vch2": "정치외교학",
    "doc1": "전남대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정경희",
    "id": 236,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정무성",
    "id": 237,
    "vch1": "숭실대",
    "vch2": "영문학",
    "doc1": "시카고대",
    "doc2": "복지행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정상호",
    "id": 238,
    "vch1": "한양대",
    "vch2": "정치외교학",
    "doc1": "고려대",
    "doc2": "정치외교학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정성훈1",
    "id": 239,
    "vch1": "동국대",
    "vch2": "지리교육학",
    "doc1": "서섹스대",
    "doc2": "경제지리학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정세은",
    "id": 240,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "파리제13대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "참여연대",
    "thumb": null
  },
  {
    "name": "정영모",
    "id": 241,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정영애",
    "id": 242,
    "vch1": "이화여대",
    "vch2": "사회학",
    "doc1": "이화여대",
    "doc2": "여성학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "정은미",
    "id": 243,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정익중",
    "id": 244,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "워싱턴대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정재훈",
    "id": 245,
    "vch1": "서울대",
    "vch2": 0,
    "doc1": "Universitaet Triel",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정준호",
    "id": 246,
    "vch1": "서울대",
    "vch2": "지리학",
    "doc1": "옥스퍼드대",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "정해구",
    "id": 247,
    "vch1": "연세대",
    "vch2": "행정학",
    "doc1": "고려대",
    "doc2": "정치외교학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "정현백",
    "id": 248,
    "vch1": "서울대",
    "vch2": "역사교육",
    "doc1": "보쿰대",
    "doc2": "독일사",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "정흥준",
    "id": 249,
    "vch1": "성균관대",
    "vch2": "전기공학",
    "doc1": "고려대",
    "doc2": "경영학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조경애1",
    "id": 250,
    "vch1": "서울대",
    "vch2": "생활과학대학",
    "doc1": "없음",
    "doc2": 0,
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조대엽",
    "id": 251,
    "vch1": "고려대",
    "vch2": "사회학",
    "doc1": "고려대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "조명래",
    "id": 252,
    "vch1": "단국대",
    "vch2": "지역개발학",
    "doc1": "서섹스대",
    "doc2": "도시 및 지역학",
    "sch": "한국공간환경학회",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "환경정의",
    "thumb": true
  },
  {
    "name": "조복현",
    "id": 253,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조봉현",
    "id": 254,
    "vch1": "동아대",
    "vch2": "경제학",
    "doc1": "동아대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조성욱",
    "id": 255,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "하버드대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "조성재",
    "id": 256,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조영철1",
    "id": 257,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조용만",
    "id": 258,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조용성",
    "id": 259,
    "vch1": "고려대",
    "vch2": "농업경제학",
    "doc1": "미네소타대",
    "doc2": "응용경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "조한범",
    "id": 260,
    "vch1": "한양대",
    "vch2": "사회학",
    "doc1": "상트페테르부르크대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조현승",
    "id": 261,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "인디애나대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조황희",
    "id": 262,
    "vch1": "전남대",
    "vch2": "화학공업경영학",
    "doc1": "카이스트",
    "doc2": "선업공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "조흥식",
    "id": 263,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "주만수",
    "id": 264,
    "vch1": "한양대",
    "vch2": "경제학",
    "doc1": "일리노이대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "주상영",
    "id": 265,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "위스콘신대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "주은선",
    "id": 266,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "주현",
    "id": 267,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "지만수",
    "id": 268,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "지은정",
    "id": 269,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "진미정",
    "id": 270,
    "vch1": "서울대",
    "vch2": "생활과학대학",
    "doc1": "펜실베이니아주립대",
    "doc2": "인간발달 및 가족학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "진영효",
    "id": 271,
    "vch1": "서울시립대",
    "vch2": 0,
    "doc1": "서울대",
    "doc2": "도시설계학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "차미숙",
    "id": 272,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "채창균",
    "id": 273,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "천현숙",
    "id": 274,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "사회학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최경숙1",
    "id": 275,
    "vch1": "경북대",
    "vch2": "농업토목공학",
    "doc1": "뉴사우스웨일스대",
    "doc2": "토목환경공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최기영",
    "id": 276,
    "vch1": "서울대",
    "vch2": "전자공학",
    "doc1": "스탠퍼드대",
    "doc2": "전기공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "최동진",
    "id": 277,
    "vch1": "서울대",
    "vch2": "도시공학",
    "doc1": "카이스트",
    "doc2": "토목공학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최상한",
    "id": 278,
    "vch1": "아주대",
    "vch2": "영어영문학",
    "doc1": "아틀란틱대",
    "doc2": "행정학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최영",
    "id": 279,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최영섭",
    "id": 280,
    "vch1": "고려대",
    "vch2": "경영학",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최영준",
    "id": 281,
    "vch1": "연세대",
    "vch2": "사회복지학",
    "doc1": "바스대",
    "doc2": "사회정책학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최옥금",
    "id": 282,
    "vch1": "성균관대",
    "vch2": "사회복지학",
    "doc1": "성균관대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최은영1",
    "id": 283,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최장호",
    "id": 284,
    "vch1": "서울대",
    "vch2": "경제학/농업자원경제학",
    "doc1": "오레곤주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최재관",
    "id": 285,
    "vch1": "서울대",
    "vch2": "응용생물학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최정표",
    "id": 286,
    "vch1": "성균관대",
    "vch2": "경제학",
    "doc1": "뉴욕주립대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "최지영",
    "id": 287,
    "vch1": "고려대",
    "vch2": "경제학",
    "doc1": "고려대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최진욱",
    "id": 288,
    "vch1": "한국외대",
    "vch2": "정치학",
    "doc1": "신시내티대",
    "doc2": "정치학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "최혜지",
    "id": 289,
    "vch1": "이화여대",
    "vch2": 0,
    "doc1": "워싱턴대 세인트루이스",
    "doc2": "사회사업학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "추장민",
    "id": 290,
    "vch1": "서울대",
    "vch2": "신문학",
    "doc1": "북경대",
    "doc2": "환경과학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "하연섭",
    "id": 291,
    "vch1": "연세대",
    "vch2": "행정학",
    "doc1": "인디애나대",
    "doc2": "정책학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "하준경",
    "id": 292,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "브라운대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "한인섭1",
    "id": 293,
    "vch1": "서울대",
    "vch2": "법학",
    "doc1": "서울대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "한현옥",
    "id": 294,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "위스콘신대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "허헌중",
    "id": 295,
    "vch1": "서울대",
    "vch2": "정치학",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍경준",
    "id": 296,
    "vch1": "서울대",
    "vch2": "사회복지학",
    "doc1": "서울대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍민기",
    "id": 297,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍성민1",
    "id": 298,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "교토대",
    "doc2": "법학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍성인",
    "id": 299,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "이화여대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍승아",
    "id": 300,
    "vch1": "연세대",
    "vch2": "사회학",
    "doc1": "연세대",
    "doc2": "사회복지학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "홍장표",
    "id": 301,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": true
  },
  {
    "name": "황덕순",
    "id": 302,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "학현학파",
    "camp": "X",
    "support": "X",
    "sch3": "참여연대",
    "thumb": true
  },
  {
    "name": "황성현",
    "id": 303,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "펜실베이니아대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "O",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "황수철",
    "id": 304,
    "vch1": "서울대",
    "vch2": "경제학",
    "doc1": "서울대",
    "doc2": "경제학",
    "sch": "없음",
    "sch2": "없음",
    "camp": "O",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "황윤재",
    "id": 305,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  },
  {
    "name": "황진회",
    "id": 306,
    "vch1": "확인불가",
    "vch2": "확인불가",
    "doc1": "확인불가",
    "doc2": "확인불가",
    "sch": "없음",
    "sch2": "없음",
    "camp": "X",
    "support": "X",
    "sch3": "없음",
    "thumb": null
  }
]